############################################################
# +------------------------------------------------------+ #
# |                       Config                         | #
# +------------------------------------------------------+ #
############################################################

# Whether chestplates can be combined with elytras.
combine: true

# Whether elytras can be separate back to chestplate and elytra.
separate: true
