############################################################
# +------------------------------------------------------+ #
# |                       Config                         | #
# +------------------------------------------------------+ #
############################################################

# Whether chestplates can be combined with elytras.
combine: true

# Whether elytras can be separate back to chestplate and elytra.
separate: true 
  
############################################################
# +------------------------------------------------------+ #
# |                      Main GUI                        | #
# +------------------------------------------------------+ #
############################################################

main-sound: 'ENTITY_PLAYER_LEVELUP'
# Sounds @ https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html

### Config ###

# Name of the container.
main-gui-name: '&d&lSakura Elytra'

# Size for custom inventory must be a multiple of 9 between 9 and 54 slots
# Essentially: 9 times how many rows. 9 = 1 row, 18 = 2 rows.
main-gui-size: 45

# Undefined slots will by default be black stained glass panes with blank names.
# ### Tags ###
# COMBINE - Marks this slot as a button to open the Combine menu.
# SEPARATE - Marks this slot as a button to open the Separate menu.
main-gui:
  '0':
    name: ''
    item: ''
    lore1: ''
    lore2: ''
    interact: false
    tag: ''
    
# ## EXAMPLE ##
# main-gui:
#   '22':
#     name: Merge
#     item: LIME_STAINED_GLASS_PANE
#     lore1: ''
#     lore2: ''
#     interact: false
#     tag: CONFIRM
  
############################################################
# +------------------------------------------------------+ #
# |                       Combine                        | #
# +------------------------------------------------------+ #
############################################################

### Lang ###

combine-success: '%plugin% &dCombination success!'

combine-fail: '%plugin% &dCombination failed!\nElytra missing, or is already combined.'

### Config ###

# Sound played when items combine.
combine-sound: 'ENTITY_PLAYER_LEVELUP'
# Sounds @ https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html

# Name of the container.
combine-gui-name: '&d&lSakura Elytra'

# Size for custom inventory must be a multiple of 9 between 9 and 54 slots
# Essentially: 9 times how many rows. 9 = 1 row, 18 = 2 rows.
combine-gui-size: 45

# Undefined slots will by default be black stained glass panes with blank names.
# ### Tags ###
# PLAYER - Slot for the player's item. return these slots to the player upon closing inventory. !IMPORTANT only 2 of these, always chestplate first.
# CONFIRM - Marks this slot as a button to confirm merging.
combine-gui:
  '0':
    name: ''
    item: ''
    lore1: ''
    lore2: ''
    interact: false
    tag: ''
    
# ## EXAMPLE ##
# combine-gui:
#   '22':
#     name: Merge
#     item: LIME_STAINED_GLASS_PANE
#     lore1: ''
#     lore2: ''
#     interact: false
#     tag: CONFIRM
  
############################################################
# +------------------------------------------------------+ #
# |                      Separate                        | #
# +------------------------------------------------------+ #
############################################################

### Lang ###

separate-success: '%plugin% &dSeparation success!'

separate-fail: '%plugin% &dSeparation failed!\nElytra missing, or is not combined.'

### Config ###

# Sound played when items combine.
separate-sound: 'ENTITY_PLAYER_LEVELUP'
# Sounds @ https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html

# Name of the container.
separate-gui-name: '&d&lSakura Elytra'

# Size for custom inventory must be a multiple of 9 between 9 and 54 slots
# Essentially: 9 times how many rows. 9 = 1 row, 18 = 2 rows.
separate-gui-size: 45

# Undefined slots will by default be black stained glass panes with blank names.
# ### Tags ###
# PLAYER - Slot for the player's item. return these slots to the player upon closing inventory. !IMPORTANT only 2 of these, always elytra first.
# CONFIRM - Marks this slot as a button to confirm merging.
separate-gui:
  '0':
    name: ''
    item: ''
    lore1: ''
    lore2: ''
    interact: false
    tag: ''
    
# ## EXAMPLE ##
# separate-gui:
#   '22':
#     name: Merge
#     item: LIME_STAINED_GLASS_PANE
#     lore1: ''
#     lore2: ''
#     interact: false
#     tag: CONFIRM

