############################################################
# +------------------------------------------------------+ #
# |                       Config                         | #
# +------------------------------------------------------+ #
############################################################

# Additional messages used for debugging.
debug: false

# Checks for updates for the plugin.
check-updates: true

# Language used when translating material and item names.
## Supported languages:
# English (US) --------- en_us
# English -------------- en_gb
# Danish --------------- da_dk
# German --------------- de_de
# Spanish -------------- es_es
# French --------------- fr_fr
# Turkish -------------- tr_tr
# Dutch ---------------- nl_nl
# Japenese ------------- ja_jp
# Korean --------------- ko_kr
# Chinese (Simplified) - zh_cn
# Russian -------------- ru_ru
# Polish --------------- pl_pl
language: 'en_us'

# Whether chestplates can be combined with elytras.
combine: true

# Requires Vault.
# Ignored if 0.
combine-cost: 0

# Whether elytras can be separate back to chestplate and elytra.
separate: true

# Requires Vault.
# Ignored if 0.
separate-cost: 0

# Custom Model Data of the combined elytra.
# If diabled, the combined elytra will inherit the CMD of the original elytra.
custommodeldata:
 enabled: false
 combined: 12070
 # Should each material type have their own?
 per-material:
  enabled: false
  leather: 12071
  iron: 12072
  gold: 12073
  chainmail: 12074
  diamond: 12075
  netherite: 12076

# Should the items take damage when separated?
# Otherwise they get fully repaired.
item-damage:
 enabled: true
 damage-chestplate: true
 damage-elytra: false
 
