############################################################
# +------------------------------------------------------+ #
# |                       Config                         | #
# +------------------------------------------------------+ #
############################################################

# Additional messages used for debugging.
debug: false

# Checks for updates for the plugin.
check-updates: true

# Language used when translating material and item names.
## Supported languages:
# English (US) --------- en_us
# English -------------- en_gb
# Danish --------------- da_dk
# German --------------- de_de
# Spanish -------------- es_es
# French --------------- fr_fr
# Turkish -------------- tr_tr
# Dutch ---------------- nl_nl
# Japenese ------------- ja_jp
# Korean --------------- ko_kr
# Chinese (Simplified) - zh_cn
# Russian -------------- ru_ru
# Polish --------------- pl_pl
language: 'en_us'

# Whether chestplates can be combined with elytras.
combine: true

# Whether elytras can be separate back to chestplate and elytra.
separate: true
