name: HavenElytra
main: valorless.havenelytra.Main
version: version-number
author: Valorless
depend: [ValorlessUtils]
softdepend: [PlaceholderAPI]
api-version: 1.18
commands:
  havenelytra:
    description: Main command.
    usage:
    aliases: he
permissions:
  havenelytra.*:
    description: Gives access to all HavenElytra commands.
    children:
      havenelytra.reload: true
      havenelytra.combine: true
      havenelytra.separate: true
  havenelytra.reload:
    description: Allows you to reload the configuration.
    default: op
  havenelytra.combine:
    description: Allows you to combine elytras.
    default: op
  havenelytra.separate:
    description: Allows you to separate elytras.
    default: op
  