name: HavenElytra
main: valorless.havenelytra.HavenElytra
version: version-number
author: Valorless
depend: [ValorlessUtils]
api-version: 1.18
commands:
  havenelytra:
    description: Main command.
    usage:
    aliases: he
  havenelytra reload:
    description: Reloads the configuration file.
    usage: /havenelytra reload
    permission: havenelytra.reload
    permission-message: You don't have havenelytra.reload.
    aliases: he reload
  havenelytra combine:
    description: Combine elytras with chestplates.
    usage: /havenelytra combine
    permission: havenelytra.combine
    permission-message: You don't have havenelytra.combine.
    aliases: he combine
  havenelytra separate:
    description: Separate chestplate from elytra.
    usage: /havenelytra separate
    permission: havenelytra.separate
    permission-message: You don't have havenelytra.separate.
    aliases: he separate
permissions:
  havenelytra.*:
    description: Gives access to all HavenElytra commands.
    children:
      havenelytra.reload: true
  havenelytra.reload:
    description: Allows you to reload the configuration.
    default: op
  