name: HavenElytra
main: valorless.havenelytra.HavenElytra
version: 1.2.0.146
author: Valorless
depend: [ValorlessUtils]
api-version: 1.18
commands:
  havenelytra:
    description: Main command.
    usage:
    aliases: he
  havenelytra reload:
    description: Reloads the configuration file.
    usage: /havenelytra reload
    permission: havenelytra.reload
    permission-message: You don't have havenelytra.reload.
    aliases: he reload
permissions:
  havenelytra.*:
    description: Gives access to all HavenElytra commands.
    children:
      havenelytra.reload: true
  havenelytra.reload:
    description: Allows you to reload the configuration.
    default: op
  