name: SakuraElytra
main: valorless.sakuraelytra.SakuraElytra
version: 1.1.0.63
author: Valorless
depend: [ValorlessUtils]
api-version: 1.18
commands:
  sakuraelytra:
    description: Main command.
    usage:
    aliases: se
  sakuraelytra reload:
    description: Reloads the configuration file.
    usage: /sakuraelytra reload
    permission: sakuraelytra.reload
    permission-message: You don't have sakuraelytra.reload.
    aliases: se reload
  sakuraelytra combine:
    description: Combine hats with helmets.
    usage: /sakuraelytra combine
    permission: sakuraelytra.combine
    permission-message: You don't have sakuraelytra.combine.
    aliases: se combine
  sakuraelytra separate:
    description: Separate chestplate from elytra.
    usage: /sakuraelytra separate
    permission: sakuraelytra.separate
    permission-message: You don't have sakuraelytra.separate.
    aliases: se separate
permissions:
  sakuraelytra.*:
    description: Gives access to all SakuraElytra commands.
    children:
      sakuraelytra.reload: true
  sakuraelytra.reload:
    description: Allows you to reload the configuration.
    default: op
  